### ISSUE TITLE
js-text-anim__wrapper does not appear to animate on iOS

### ISSUE THREAD

**Issue by ItsMorePaul** [CodyHouse/cd-giove-changelog#1]
Animated text on About page template does not appear to work on iOS.

![Giove  Portfolio template by CodyHouse](https://user-images.githubusercontent.com/49879648/132905584-d213cc50-6e3d-47df-b93b-688db00cbb3d.jpeg)

**Comment by claudia-romano** [comment]
Hi Paul, what iOS version are you using? Just tested it on iOS14 and it works fine. Thanks!

**Comment by ItsMorePaul** [comment]
Hi Claudia, I'm using iOS 15.0 (19A5340a)  - issue appears in Chrome and Safari on this version.

**Comment by claudia-romano** [comment]
Hi Paul, it's a iOS15 bug only (working fine in iOS14). 
Since it's still a beta, we won't be fixing it now as this may be solved with the stable version. I'm closing this for now. We'll reopen the issue if it still exists once iOS15 is released. Cheers!
