### ISSUE TITLE
Close button does not work on iOS

### ISSUE THREAD

**Issue by ItsMorePaul** [CodyHouse/cd-giove-changelog#2]
Close button for the following pages do not work, pressing does nothing:
1. About
2. Work
3. Contact

![Giove  Portfolio template by CodyHouse](https://user-images.githubusercontent.com/49879648/132905830-cf854de1-3a6f-4045-8ba8-9eb78ac84e79.jpeg)

**Comment by claudia-romano** [comment]
Same as https://github.com/CodyHouse/cd-giove-changelog/issues/1

**Comment by ItsMorePaul** [comment]
Hi Claudia, I'm using iOS 15.0 (19A5340a) - issue appears in Chrome and Safari on this version.

**Comment by claudia-romano** [comment]
Same as https://github.com/CodyHouse/cd-giove-changelog/issues/1.
Closing this for now. We'll reopen if the bug is not solved in iOS15 stable version.
